import cv2 as cv
img1=cv.imread("img1.jpg")
img2=cv.imread("img2.jpg")
img3=cv.imread("img3.jpg")
img4=cv.imread("img4.webp")
img5=cv.imread("img5.jpg")
img6=cv.imread("img6.jpg")
size1=(400,400)
temp1=cv.resize(img1,size1)
temp2=cv.resize(img2,size1)
temp3=cv.resize(img3,size1)
temp4=cv.resize(img4,size1)
temp5=cv.resize(img5,size1)
temp6=cv.resize(img6,size1)
imgconcat1=cv.hconcat([temp1,temp2,temp3])
imgconcat2=cv.hconcat([temp4,temp5,temp6])
imgconcat3=cv.vconcat([imgconcat1,imgconcat2])
cv.imshow("collage1",imgconcat3)
